pipeline {
    agent any
     stages {
           stage('Build Application') {
            steps {
                def mvnHome = tool name: 'Apache Maven 3.8.1', type: 'LocalMaven'
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
       
    }
}
